# uFE ------------------------------------------------------------------------

# 1) Reconstruction
DEFAULT_START_SLICE = 2000
DEFAULT_END_SLICE = 3200
DEFAULT_THRESH_LOWER = 80
DEFAULT_THRESH_UPPER = 255

# QA
DEFAULT_MAX_HOLE_SIZE = 500

# 4) Initial volume
DEFAULT_ELEMENT_SIZE = 100

# 6) Adaptive meshing
DEFAULT_HAUSD = 1e-2
DEFAULT_HGRAD = 1.3
DEFAULT_HMIN = 1e0
DEFAULT_HMAX = 1e2
DEFAULT_SUBDOMAIN = 3
DEFAULT_MEMORY_MAX = 16000
DEFAULT_MESH_ITERATIONS = 1
